/**
 * offline_import.js
 *
 * Imports all known offline Pokkén Tournament events from Liquipedia into Neos City.
 * Source: https://liquipedia.net/fighters/Pokkén_Tournament/Tournaments
 *
 * Run from the neos-city directory with the backend running:
 *   node offline_import.js
 *
 * Safe to re-run — already-imported events are skipped.
 */

const axios = require('axios');

const BACKEND_URL = 'http://localhost:3001';

// All offline Pokkén Tournament events from Liquipedia (2016–2026)
// Fields: name, date (YYYY-MM-DD), location, prize_pool, participants_count, winner, runner_up, liquipedia_slug
const OFFLINE_TOURNAMENTS = [
  // ── 2026 ─────────────────────────────────────────────────────────────────
  {
    name: 'Vortex Gallery at Frosty Faustings XVIII',
    date: '2026-01-31',
    location: 'Lombard, IL',
    prize_pool: '$379.25',
    participants_count: 24,
    winner: 'Jukem',
    runner_up: 'Shadowcat',
    liquipedia_slug: 'frosty_faustings_18',
  },

  // ── 2025 ─────────────────────────────────────────────────────────────────
  {
    name: 'CEO 2025',
    date: '2025-06-14',
    location: 'Orlando, FL',
    prize_pool: '$110',
    participants_count: 11,
    winner: 'YungBlastoiseMain42',
    runner_up: 'Kino',
    liquipedia_slug: 'ceo_2025',
  },
  {
    name: 'Vortex Gallery at Frosty Faustings XVII',
    date: '2025-01-23',
    location: 'Lombard, IL',
    prize_pool: '$252.50',
    participants_count: 24,
    winner: 'Trevwerd',
    runner_up: 'Virtigris',
    liquipedia_slug: 'frosty_faustings_17',
  },

  // ── 2024 ─────────────────────────────────────────────────────────────────
  {
    name: 'FightClub Championship V',
    date: '2024-07-28',
    location: 'Shenzhen',
    prize_pool: null,
    participants_count: 15,
    winner: 'Kapo',
    runner_up: 'Gu',
    liquipedia_slug: 'fightclub_championship_5',
  },
  {
    name: 'CEO 2024',
    date: '2024-06-29',
    location: 'Daytona Beach, FL',
    prize_pool: '$105',
    participants_count: 21,
    winner: 'Stephmicky',
    runner_up: 'Jin',
    liquipedia_slug: 'ceo_2024',
  },
  {
    name: 'Vortex Gallery at Frosty Faustings XVI',
    date: '2024-01-27',
    location: 'Lombard, IL',
    prize_pool: '$433.15',
    participants_count: 32,
    winner: 'TEC',
    runner_up: 'Jin',
    liquipedia_slug: 'frosty_faustings_16',
  },

  // ── 2023 ─────────────────────────────────────────────────────────────────
  {
    name: 'OzHadou Nationals 17',
    date: '2023-11-26',
    location: 'Bankstown',
    prize_pool: '$92.13',
    participants_count: 14,
    winner: 'Jamesibell',
    runner_up: 'Santa',
    liquipedia_slug: 'ozhadou_nationals_17',
  },
  {
    name: 'Curtain Call',
    date: '2023-10-12',
    location: 'New York, NY',
    prize_pool: '$1,850',
    participants_count: 33,
    winner: 'TEC',
    runner_up: 'Mewtater',
    liquipedia_slug: 'curtain_call_2023',
  },
  {
    name: 'CEO 2023',
    date: '2023-06-25',
    location: 'Daytona Beach, FL',
    prize_pool: '$120',
    participants_count: 24,
    winner: 'Jin',
    runner_up: '99dash',
    liquipedia_slug: 'ceo_2023',
  },
  {
    name: 'Battle Arena Melbourne 13',
    date: '2023-06-11',
    location: 'Melbourne',
    prize_pool: '$67.37',
    participants_count: 20,
    winner: 'IceBurgy',
    runner_up: 'Antwerp',
    liquipedia_slug: 'bam_13',
  },
  {
    name: 'All In Together 2023',
    date: '2023-05-28',
    location: 'Schaumburg, IL',
    prize_pool: '$75',
    participants_count: 15,
    winner: 'Jin',
    runner_up: 'Mins',
    liquipedia_slug: 'all_in_together_2023',
  },
  {
    name: 'Frosty Faustings XV',
    date: '2023-02-03',
    location: 'Lombard, IL',
    prize_pool: '$270',
    participants_count: 54,
    winner: 'Mewtater',
    runner_up: 'TEC',
    liquipedia_slug: 'frosty_faustings_15',
  },

  // ── 2022 ─────────────────────────────────────────────────────────────────
  {
    name: 'Frostfire 2022',
    date: '2022-12-03',
    location: 'Gatineau',
    prize_pool: '$423.91',
    participants_count: 20,
    winner: 'Jukem',
    runner_up: 'TEC',
    liquipedia_slug: 'frostfire_2022',
  },
  {
    name: 'Pokkén Tournament DX World Championships 2022',
    date: '2022-08-19',
    location: 'London',
    prize_pool: '$20,000',
    participants_count: 16,
    winner: 'Shadowcat',
    runner_up: 'Mewtater',
    liquipedia_slug: 'worlds_2022',
  },
  {
    name: 'North American International Championships 2022',
    date: '2022-06-26',
    location: 'Columbus, OH',
    prize_pool: '$5,000',
    participants_count: null,
    winner: 'Mewtater',
    runner_up: 'Elm',
    liquipedia_slug: 'naic_2022',
  },
  {
    name: 'Battle Arena Melbourne 12',
    date: '2022-05-15',
    location: 'Melbourne',
    prize_pool: '$125.02',
    participants_count: 18,
    winner: 'Antwerp',
    runner_up: 'Santa',
    liquipedia_slug: 'bam_12',
  },
  {
    name: 'European International Championships 2022',
    date: '2022-04-23',
    location: 'Frankfurt',
    prize_pool: '$5,000',
    participants_count: 15,
    winner: 'M2Cloud',
    runner_up: 'Elm',
    liquipedia_slug: 'eic_2022',
  },
  {
    name: 'Frosty Faustings XIV',
    date: '2022-01-29',
    location: 'Lombard, IL',
    prize_pool: '$310',
    participants_count: 62,
    winner: 'Jukem',
    runner_up: 'Rokso',
    liquipedia_slug: 'frosty_faustings_14',
  },

  // ── 2021 ─────────────────────────────────────────────────────────────────
  {
    name: 'Northeast Championship 21',
    date: '2021-11-06',
    location: 'Philadelphia',
    prize_pool: '$430',
    participants_count: 43,
    winner: 'Jukem',
    runner_up: 'TEC',
    liquipedia_slug: 'nec_21',
  },

  // ── 2020 ─────────────────────────────────────────────────────────────────
  {
    name: 'DreamHack Anaheim 2020',
    date: '2020-02-23',
    location: 'Anaheim, CA',
    prize_pool: '$1,000',
    participants_count: 47,
    winner: 'Mewtater',
    runner_up: 'slippingbug',
    liquipedia_slug: 'dreamhack_anaheim_2020',
  },
  {
    name: 'Frostfire 2020',
    date: '2020-02-01',
    location: 'Gatineau',
    prize_pool: '$1,218.97',
    participants_count: 31,
    winner: 'Jukem',
    runner_up: 'Mewtater',
    liquipedia_slug: 'frostfire_2020',
  },
  {
    name: 'Frosty Faustings XII',
    date: '2020-01-17',
    location: 'Wheeling, IL',
    prize_pool: '$520',
    participants_count: 52,
    winner: 'Shadowcat',
    runner_up: 'Mewtater',
    liquipedia_slug: 'frosty_faustings_12',
  },

  // ── 2019 ─────────────────────────────────────────────────────────────────
  {
    name: 'Northeast Championship 20',
    date: '2019-11-30',
    location: 'Lancaster, PA',
    prize_pool: '$310',
    participants_count: 31,
    winner: 'Euclase',
    runner_up: 'Rokso',
    liquipedia_slug: 'nec_20',
  },
  {
    name: 'Revolution 2019',
    date: '2019-10-11',
    location: 'London',
    prize_pool: '$118.13',
    participants_count: 19,
    winner: 'Kuromu',
    runner_up: 'Kira A',
    liquipedia_slug: 'revolution_2019',
  },
  {
    name: 'Summer Jam 13',
    date: '2019-08-30',
    location: 'Essington',
    prize_pool: '$130',
    participants_count: 13,
    winner: 'Flegar',
    runner_up: 'NG-Obscure',
    liquipedia_slug: 'summer_jam_13',
  },
  {
    name: 'Pokkén Tournament DX World Championships 2019',
    date: '2019-08-18',
    location: 'Washington, DC',
    prize_pool: '$20,000',
    participants_count: 16,
    winner: 'Subutan',
    runner_up: 'Haruyuki',
    liquipedia_slug: 'worlds_2019',
  },
  {
    name: 'EVO 2019',
    date: '2019-08-03',
    location: 'Las Vegas, NV',
    prize_pool: '$350',
    participants_count: 35,
    winner: 'Mewtater',
    runner_up: 'Twixxie',
    liquipedia_slug: 'evo_2019',
  },
  {
    name: 'Defend the North 2019',
    date: '2019-07-19',
    location: 'New York City, NY',
    prize_pool: null,
    participants_count: 28,
    winner: 'Kamon',
    runner_up: 'BmX',
    liquipedia_slug: 'defend_the_north_2019',
  },
  {
    name: 'Toryuken 8',
    date: '2019-07-14',
    location: 'Toronto, ON',
    prize_pool: '$260.23',
    participants_count: 34,
    winner: 'Mewtater',
    runner_up: 'Wise',
    liquipedia_slug: 'toryuken_8',
  },
  {
    name: 'North America International Championships 2019',
    date: '2019-06-23',
    location: 'Columbus, OH',
    prize_pool: '$5,000',
    participants_count: 46,
    winner: 'Mewtater',
    runner_up: 'ELM',
    liquipedia_slug: 'naic_2019',
  },
  {
    name: 'Europe International Championships 2019',
    date: '2019-04-28',
    location: 'Berlin',
    prize_pool: '$5,000',
    participants_count: 31,
    winner: 'DefenderOfEU',
    runner_up: 'Potetin',
    liquipedia_slug: 'eic_2019',
  },
  {
    name: 'NorCal Regionals 2019',
    date: '2019-03-29',
    location: 'San Jose, CA',
    prize_pool: '$320',
    participants_count: 32,
    winner: 'Wingtide',
    runner_up: 'Jin',
    liquipedia_slug: 'ncr_2019',
  },
  {
    name: 'Final Round 2019',
    date: '2019-03-15',
    location: 'Atlanta, GA',
    prize_pool: '$170',
    participants_count: 17,
    winner: 'ThankSwalot',
    runner_up: 'Raikel',
    liquipedia_slug: 'final_round_2019',
  },
  {
    name: 'Winter Brawl 3D 2019',
    date: '2019-02-24',
    location: 'Essington, PA',
    prize_pool: '$340',
    participants_count: 34,
    winner: 'Wingtide',
    runner_up: 'Euclase',
    liquipedia_slug: 'winter_brawl_2019',
  },
  {
    name: 'Oceania International Championships 2019',
    date: '2019-02-17',
    location: 'Melbourne',
    prize_pool: '$5,000',
    participants_count: 23,
    winner: 'Elm',
    runner_up: 'CrossIgarashi',
    liquipedia_slug: 'oic_2019',
  },
  {
    name: 'Frostfire 2019',
    date: '2019-01-26',
    location: 'Gatineau',
    prize_pool: '$621.80',
    participants_count: 23,
    winner: 'Wise',
    runner_up: 'In The Groove',
    liquipedia_slug: 'frostfire_2019',
  },
  {
    name: 'Frosty Faustings XI',
    date: '2019-01-19',
    location: 'Elmhurst',
    prize_pool: '$980',
    participants_count: 48,
    winner: 'Wingtide',
    runner_up: 'ThankSwalot',
    liquipedia_slug: 'frosty_faustings_11',
  },

  // ── 2018 ─────────────────────────────────────────────────────────────────
  {
    name: 'Northeast Championship 19',
    date: '2018-12-16',
    location: 'King of Prussia, PA',
    prize_pool: '$300',
    participants_count: 30,
    winner: 'Wingtide',
    runner_up: 'ThankSwalot',
    liquipedia_slug: 'nec_19',
  },
  {
    name: 'Destiny 2018',
    date: '2018-11-11',
    location: 'Elizabeth, NJ',
    prize_pool: '$2,500',
    participants_count: 100,
    winner: 'Euclase',
    runner_up: 'Mewtater',
    liquipedia_slug: 'destiny_2018',
  },
  {
    name: 'Canada Cup 2018',
    date: '2018-10-28',
    location: 'Toronto, ON',
    prize_pool: null,
    participants_count: 28,
    winner: 'Adelvos',
    runner_up: 'TytoVortex',
    liquipedia_slug: 'canada_cup_2018',
  },
  {
    name: 'Eye of the Storm 2018',
    date: '2018-10-14',
    location: 'Omaha, NE',
    prize_pool: '$960',
    participants_count: 41,
    winner: 'ThankSwalot',
    runner_up: 'Twixxie',
    liquipedia_slug: 'eye_of_the_storm_2018',
  },
  {
    name: 'Revolution 2018',
    date: '2018-09-30',
    location: 'London',
    prize_pool: '$149.94',
    participants_count: 23,
    winner: 'Wingtide',
    runner_up: 'Gintrax',
    liquipedia_slug: 'revolution_2018',
  },
  {
    name: 'SoCal Regionals 2018',
    date: '2018-09-16',
    location: 'Ontario, CA',
    prize_pool: '$200',
    participants_count: 20,
    winner: 'Allister',
    runner_up: 'ThunderGriffin',
    liquipedia_slug: 'scr_2018',
  },
  {
    name: 'Summer Jam 12',
    date: '2018-09-02',
    location: 'Cherry Hill, NJ',
    prize_pool: '$230',
    participants_count: 23,
    winner: 'Flegar',
    runner_up: 'Son_Dula',
    liquipedia_slug: 'summer_jam_12',
  },
  {
    name: 'Pokkén Tournament DX World Championships 2018',
    date: '2018-08-26',
    location: 'Nashville, TN',
    prize_pool: '$20,000',
    participants_count: 16,
    winner: 'ThankSwalot',
    runner_up: 'TARUTARO',
    liquipedia_slug: 'worlds_2018',
  },
  {
    name: 'EVO 2018',
    date: '2018-08-03',
    location: 'Las Vegas, NV',
    prize_pool: '$770',
    participants_count: 52,
    winner: 'Twixxie',
    runner_up: 'Azazel',
    liquipedia_slug: 'evo_2018',
  },
  {
    name: 'Defend the North 2018',
    date: '2018-07-22',
    location: 'White Plains, NY',
    prize_pool: '$340',
    participants_count: 34,
    winner: 'Twixxie',
    runner_up: 'Euclase',
    liquipedia_slug: 'defend_the_north_2018',
  },
  {
    name: 'DreamHack Austin 2018',
    date: '2018-06-02',
    location: 'Austin, TX',
    prize_pool: '$1,000',
    participants_count: 120,
    winner: 'slippingbug',
    runner_up: 'Twixxie',
    liquipedia_slug: 'dreamhack_austin_2018',
  },
  {
    name: 'NorCal Regionals 2018',
    date: '2018-04-01',
    location: 'Sacramento, CA',
    prize_pool: '$360',
    participants_count: 36,
    winner: 'ThankSwalot',
    runner_up: 'slippingbug',
    liquipedia_slug: 'ncr_2018',
  },
  {
    name: 'Final Round 2018',
    date: '2018-03-16',
    location: 'Atlanta, GA',
    prize_pool: '$340',
    participants_count: 34,
    winner: 'Twixxie',
    runner_up: 'ThankSwalot',
    liquipedia_slug: 'final_round_2018',
  },
  {
    name: 'Winter Brawl 12',
    date: '2018-02-25',
    location: 'Essington, PA',
    prize_pool: '$500',
    participants_count: 75,
    winner: 'Twixxie',
    runner_up: 'ThankSwalot',
    liquipedia_slug: 'winter_brawl_2018',
  },
  {
    name: 'Frosty Faustings X',
    date: '2018-01-21',
    location: 'Elmhurst',
    prize_pool: '$510',
    participants_count: 51,
    winner: 'slippingbug',
    runner_up: 'Twixxie',
    liquipedia_slug: 'frosty_faustings_10',
  },
  {
    name: 'GENESIS 5',
    date: '2018-01-20',
    location: 'Oakland, CA',
    prize_pool: '$320',
    participants_count: 32,
    winner: 'ALLISTER',
    runner_up: 'Mewtater',
    liquipedia_slug: 'genesis_5',
  },

  // ── 2017 ─────────────────────────────────────────────────────────────────
  {
    name: 'Northeast Championship 18',
    date: '2017-12-15',
    location: 'King of Prussia, PA',
    prize_pool: '$1,540',
    participants_count: 54,
    winner: 'RoksoTheSavage',
    runner_up: 'ThankSwalot',
    liquipedia_slug: 'nec_18',
  },
  {
    name: 'Final Boss 2017',
    date: '2017-10-29',
    location: 'Newark, NJ',
    prize_pool: '$3,440',
    participants_count: 94,
    winner: 'Azazel',
    runner_up: 'slippingbug',
    liquipedia_slug: 'final_boss_2017',
  },
  {
    name: 'The Fall Classic 2017',
    date: '2017-10-01',
    location: 'Raleigh, NC',
    prize_pool: '$1,250',
    participants_count: 20,
    winner: 'Twixxie',
    runner_up: 'Raedis',
    liquipedia_slug: 'fall_classic_2017',
  },
  {
    name: 'SoCal Regionals 2017',
    date: '2017-09-24',
    location: 'Anaheim, CA',
    prize_pool: '$1,340',
    participants_count: 34,
    winner: 'Allister',
    runner_up: 'Coach Steve',
    liquipedia_slug: 'scr_2017',
  },
  {
    name: 'Pokkén Tournament World Championships 2017',
    date: '2017-08-19',
    location: 'Anaheim, CA',
    prize_pool: '$20,000',
    participants_count: 16,
    winner: 'Tonosama',
    runner_up: 'Mikukey_Homura',
    liquipedia_slug: 'worlds_2017',
  },
  {
    name: 'Summer Jam XI',
    date: '2017-08-11',
    location: 'Philadelphia, PA',
    prize_pool: '$1,370',
    participants_count: 37,
    winner: 'Twixxie',
    runner_up: 'SoulGuitarist',
    liquipedia_slug: 'summer_jam_11',
  },
  {
    name: 'EVO 2017',
    date: '2017-07-16',
    location: 'Las Vegas, NV',
    prize_pool: '$3,320',
    participants_count: 53,
    winner: 'Suicune Master',
    runner_up: 'SuperTurboRyan',
    liquipedia_slug: 'evo_2017',
  },
  {
    name: 'DreamHack Summer 2017',
    date: '2017-06-18',
    location: 'Jönköping',
    prize_pool: '$5,000',
    participants_count: 36,
    winner: 'Fabilous',
    runner_up: 'XAbsoluted',
    liquipedia_slug: 'dreamhack_summer_2017',
  },
  {
    name: 'CEO 2017',
    date: '2017-06-17',
    location: 'Orlando, FL',
    prize_pool: '$6,210',
    participants_count: 121,
    winner: 'Suicune Master',
    runner_up: 'Thulius',
    liquipedia_slug: 'ceo_2017',
  },
  {
    name: 'DreamHack Austin 2017',
    date: '2017-04-30',
    location: 'Austin',
    prize_pool: '$3,000',
    participants_count: 72,
    winner: 'SlippingBug',
    runner_up: 'Suicune Master',
    liquipedia_slug: 'dreamhack_austin_2017',
  },
  {
    name: 'NorCal Regionals 2017',
    date: '2017-04-16',
    location: 'Sacramento, CA',
    prize_pool: '$320',
    participants_count: 32,
    winner: 'Slippingbug',
    runner_up: 'Double',
    liquipedia_slug: 'ncr_2017',
  },
  {
    name: 'Final Round 20',
    date: '2017-03-12',
    location: 'Atlanta, GA',
    prize_pool: '$1,060',
    participants_count: 106,
    winner: 'Twixxie',
    runner_up: 'Zyflair',
    liquipedia_slug: 'final_round_20',
  },
  {
    name: 'Winter Brawl 11',
    date: '2017-02-19',
    location: 'Essington, PA',
    prize_pool: null,
    participants_count: null,
    winner: 'Cat Fight',
    runner_up: 'LingLing',
    liquipedia_slug: 'winter_brawl_2017',
  },
  {
    name: 'Frosty Faustings IX',
    date: '2017-01-27',
    location: 'Elmhurst, IL',
    prize_pool: '$270',
    participants_count: 27,
    winner: 'Thulius',
    runner_up: 'Coach Steve',
    liquipedia_slug: 'frosty_faustings_9',
  },
  {
    name: 'Kumite In Tennessee 2017',
    date: '2017-01-08',
    location: 'Nashville, TN',
    prize_pool: '$170',
    participants_count: 17,
    winner: 'SlippingBug',
    runner_up: 'Ouroboro',
    liquipedia_slug: 'kumite_in_tennessee_2017',
  },
  {
    name: 'Smash Conference LXIX',
    date: '2017-01-07',
    location: 'Orlando',
    prize_pool: '$570',
    participants_count: 31,
    winner: 'Suicune Master',
    runner_up: 'Kukkii',
    liquipedia_slug: 'smash_conference_69',
  },

  // ── 2016 ─────────────────────────────────────────────────────────────────
  {
    name: 'Northeast Championship 17',
    date: '2016-12-18',
    location: 'King of Prussia, PA',
    prize_pool: null,
    participants_count: null,
    winner: 'Potetin',
    runner_up: 'Apollo',
    liquipedia_slug: 'nec_17',
  },
  {
    name: 'Canada Cup 2016',
    date: '2016-10-30',
    location: 'Toronto, ON',
    prize_pool: '$216.49',
    participants_count: 29,
    winner: 'Azazel',
    runner_up: 'InTheGroove',
    liquipedia_slug: 'canada_cup_2016',
  },
  {
    name: 'Summer Jam X',
    date: '2016-08-21',
    location: 'Essington',
    prize_pool: '$320',
    participants_count: null,
    winner: 'Rasenryu',
    runner_up: 'TheAppleBoom',
    liquipedia_slug: 'summer_jam_10',
  },
  {
    name: 'Pokkén Tournament World Championships 2016',
    date: '2016-08-21',
    location: 'San Francisco, CA',
    prize_pool: '$20,000',
    participants_count: 64,
    winner: 'Potetin',
    runner_up: 'Azazel',
    liquipedia_slug: 'worlds_2016',
  },
  {
    name: 'Defend the North 2016',
    date: '2016-07-30',
    location: 'New York City',
    prize_pool: null,
    participants_count: 27,
    winner: 'Suicune Master',
    runner_up: 'Bosshog',
    liquipedia_slug: 'defend_the_north_2016',
  },
  {
    name: 'EVO 2016',
    date: '2016-07-16',
    location: 'Las Vegas, NV',
    prize_pool: '$21,800',
    participants_count: 1180,
    winner: 'Tonosama',
    runner_up: 'buntan',
    liquipedia_slug: 'evo_2016',
  },
  {
    name: 'CEO 2016',
    date: '2016-06-26',
    location: 'Orlando, FL',
    prize_pool: '$7,490',
    participants_count: 249,
    winner: 'Suicune Master',
    runner_up: 'TeeJay',
    liquipedia_slug: 'ceo_2016',
  },
  {
    name: 'DreamHack Summer 2016',
    date: '2016-06-19',
    location: 'Jönköping',
    prize_pool: '$10,000',
    participants_count: 48,
    winner: 'AngelDarksong',
    runner_up: 'Justinpig',
    liquipedia_slug: 'dreamhack_summer_2016',
  },
  {
    name: 'DreamHack Austin 2016',
    date: '2016-05-08',
    location: 'Austin, TX',
    prize_pool: '$5,000',
    participants_count: 105,
    winner: 'Bim?',
    runner_up: 'Cat Fight',
    liquipedia_slug: 'dreamhack_austin_2016',
  },
  {
    name: 'Texas Showdown 2016',
    date: '2016-04-24',
    location: 'Houston, TX',
    prize_pool: null,
    participants_count: null,
    winner: 'Weegee',
    runner_up: 'NYChrisG',
    liquipedia_slug: 'texas_showdown_2016',
  },
  {
    name: 'Final Round 19',
    date: '2016-03-20',
    location: 'Atlanta, GA',
    prize_pool: null,
    participants_count: null,
    winner: 'GO1',
    runner_up: 'TheAppleBOOM',
    liquipedia_slug: 'final_round_19',
  },
];

async function main() {
  console.log(`\n🏆 Neos City — Offline Tournament Importer`);
  console.log(`📡 Backend: ${BACKEND_URL}`);
  console.log(`📋 Tournaments to import: ${OFFLINE_TOURNAMENTS.length}\n`);

  // Health check
  try {
    await axios.get(`${BACKEND_URL}/api/tournaments?is_offline=false`);
  } catch (err) {
    console.error(`❌ Cannot reach backend at ${BACKEND_URL}. Is it running?`);
    console.error(`   Start it with: cd neos-city/backend && npm run dev`);
    process.exit(1);
  }

  const res = await axios.post(`${BACKEND_URL}/api/tournaments/batch-import-offline`, {
    tournaments: OFFLINE_TOURNAMENTS,
  });

  const { imported, skipped, errors, detail } = res.data;
  console.log(`✅ Imported:  ${imported}`);
  console.log(`⏭️  Skipped:   ${skipped} (already in DB)`);
  console.log(`❌ Errors:    ${errors}`);

  if (detail.errors.length > 0) {
    console.log('\nFailed imports:');
    detail.errors.forEach(e => console.log(`  - ${e.name}: ${e.error}`));
  }

  console.log('\nDone!');
}

main().catch(err => {
  console.error('Fatal error:', err.message);
  process.exit(1);
});
